timeout: "1200s"
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "us-central1"
  _PROJECT_ID: "recommender-api-476122"
  _REPO: "reco"
  _SERVICE: "reco-api"

steps:
# Build the image from docker/service.Dockerfile
- name: gcr.io/cloud-builders/docker
  id: build
  args:
    - build
    - -f
    - docker/service.Dockerfile
    - -t
    - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE}:latest
    - .

# Push it
- name: gcr.io/cloud-builders/docker
  id: push
  args:
    - push
    - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE}:latest

# Deploy to Cloud Run
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: deploy
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ${_SERVICE}
    - --image
    - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE}:latest
    - --region
    - ${_REGION}
    - --platform=managed
    - --allow-unauthenticated
    - --set-env-vars
    - MODEL_REGISTRY=/app/model_registry

images:
- ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE}:latest
