# Build image and deploy to Cloud Run

timeout: "1200s"
options:
  logging: CLOUD_LOGGING_ONLY

# substitutions:
#   _REGION: "us-central1"
#   _PROJECT_ID: "recommender-api-476122"
#   _REPO: "reco"
#   _SERVICE: "reco-api"

steps:
# Build the image from service.Dockerfile
- name: gcr.io/cloud-builders/docker
  id: build
  args:
    - build
    - -f
    - docker/service.Dockerfile
    - -t
    - us-central1-docker.pkg.dev/recommender-api-476122/reco/reco-api
    - .

# Push it
- name: gcr.io/cloud-builders/docker
  id: push
  args:
    - push
    - us-central1-docker.pkg.dev/recommender-api-476122/reco/reco-api

# Deploy to Cloud Run
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: deploy
  entrypoint: gcloud
  args:
    - run
    - deploy
    # - ${_SERVICE}
    - reco-api
    - --image
    - us-central1-docker.pkg.dev/recommender-api-476122/reco/reco-api
    - --region
    # - ${_REGION}
    - us-central1
    - --platform=managed
    - --allow-unauthenticated
    - --set-env-vars
    - MODEL_REGISTRY_ROOT=/app/model_registry

images:
- us-central1-docker.pkg.dev/recommender-api-476122/reco/reco-api
