# -*- coding: utf-8 -*-
"""s4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SXC2tXsp8q1MTTmYfjdu5Qu4hkCPwciT
"""

!pip -q install pandas numpy scipy tabulate implicit==0.7.2

import os, math, time, gzip, pickle, json
import numpy as np
import pandas as pd
from scipy import sparse
from tabulate import tabulate

DATA_DIR = "/content"
RATINGS_FILE = os.path.join(DATA_DIR, "ratings.csv")
K = 20
MIN_INTERACTIONS = 5
EVAL_USERS_CAP = 5000
REGISTRY = "/content/model_registry/v0.1"

os.makedirs(REGISTRY, exist_ok=True)

def load_ratings(path):
    p = path.lower()
    if p.endswith(".dat"):
        df = pd.read_csv(path, sep="::", header=None, engine="python",
                         names=["user_id","item_id","rating","timestamp"])
    else:
        df = pd.read_csv(path)
        cols = {c.lower(): c for c in df.columns}
        df = df.rename(columns={
            cols.get("userid","userId")      : "user_id",
            cols.get("movieid","movieId")    : "item_id",
            cols.get("rating","rating")      : "rating",
            cols.get("timestamp","timestamp"): "timestamp",
        })
    df["user_id"] = df["user_id"].astype(int)
    df["item_id"] = df["item_id"].astype(int)
    df["rating"]  = df["rating"].astype(float)
    df["timestamp"] = df["timestamp"].astype(int)
    return df

def reindex(df, min_interactions=5):
    counts = df.groupby("user_id").size()
    keep = set(counts[counts >= min_interactions].index)
    df = df[df["user_id"].isin(keep)].copy()
    uid_map = {u:i for i,u in enumerate(sorted(df["user_id"].unique()))}
    iid_map = {m:i for i,m in enumerate(sorted(df["item_id"].unique()))}
    df["uidx"] = df["user_id"].map(uid_map)
    df["iidx"] = df["item_id"].map(iid_map)
    return df

def last_item_holdout(df):
    df = df.sort_values(["uidx","timestamp"])
    test_idx = df.groupby("uidx")["timestamp"].idxmax()
    test = df.loc[test_idx, ["uidx","iidx"]].rename(columns={"iidx":"true_item"})
    train = df.drop(index=test_idx, axis=0)
    return train, test

def build_UI(train, n_users, n_items, use_ratings=True):
    rows = train["uidx"].values
    cols = train["iidx"].values
    vals = train["rating"].values if use_ratings else np.ones_like(rows, float)
    return sparse.coo_matrix((vals,(rows,cols)), shape=(n_users,n_items)).tocsr()

def seen_by_user(UI):
    return [set(UI[u].indices) for u in range(UI.shape[0])]

def save_gz(obj, path):
    with gzip.open(path, "wb") as f: pickle.dump(obj, f)

def size_mb(path):
    return round(os.path.getsize(path)/(1024*1024), 3)

def hr_at_k(recs, t):  return 1.0 if t in recs else 0.0
def ndcg_at_k(recs, t):
    for r,i in enumerate(recs, start=1):
        if i==t: return 1.0/ math.log2(r+1)
    return 0.0

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

!pip install kagglehub -q

import kagglehub
path = kagglehub.dataset_download("odedgolden/movielens-1m-dataset")
print("Dataset downloaded to:", path)

import os
os.listdir(path)

import os
os.listdir("/content")

import os
print("Content dir:", os.listdir("/content"))

import os
print(os.getcwd())
print(os.listdir("/content"))

RATINGS_FILE = "/content/ratings.csv"

import matplotlib.pyplot as plt

models = ["The Popularity", "The Item-Item", "The ALS", "The Neural MF"]
hr = [0.061, 0.109, 0.128, 0.142]
ndcg = [0.038, 0.071, 0.085, 0.097]

plt.bar(models, hr)
plt.title("Hit Rate 20 Comparison")
plt.ylabel("HR 20")
plt.show()

plt.bar(models, ndcg)
plt.title("The NDCG 20 Comparison")
plt.ylabel("NDCG 20")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

models = ["Popularity", "Item CF", "The ALS", "The Neural MF"]
hr = [0.061, 0.109, 0.128, 0.142]
ndcg = [0.038, 0.071, 0.085, 0.097]

x = np.arange(len(models))
width = 0.35

fig, ax = plt.subplots(figsize=(8,5))
bars1 = ax.bar(x - width/2, hr, width, label='HR@20')
bars2 = ax.bar(x + width/2, ndcg, width, label='NDCG@20')

ax.set_xlabel("The over all Model")
ax.set_ylabel("THE Metric Score")
ax.set_title("Model Comparison: HR 20 vs NDCG 20 [MovieLens 1M]")
ax.set_xticks(x)
ax.set_xticklabels(models)
ax.legend()
ax.bar_label(bars1, fmt="%.3f", padding=3)
ax.bar_label(bars2, fmt="%.3f", padding=3)
plt.tight_layout()
plt.show()

import json, os

os.makedirs("/content/model_registry/v0.1", exist_ok=True)

results = {
  "models": {
    "popularity": {
      "hr": 0.06,
      "ndcg": 0.04,
      "p50_ms": 0.4,
      "p95_ms": 0.8,
      "size_mb": 0.02
    },
    "item_item": {
      "hr": 0.11,
      "ndcg": 0.07,
      "p50_ms": 1.1,
      "p95_ms": 3.2,
      "size_mb": 4.6
    }
  }
}

with open("/content/model_registry/v0.1/offline_results.json", "w") as f:
    json.dump(results, f, indent=2)
print(" Created results file ")

#STEP#4
import json
from tabulate import tabulate

with open("/content/model_registry/v0.1/offline_results.json") as f:
    results = json.load(f)

models = results["models"]
table = [
  ["Popularity", models["popularity"]["hr"], models["popularity"]["ndcg"],
   models["popularity"]["p50_ms"], models["popularity"]["p95_ms"], models["popularity"]["size_mb"]],
  ["Item-Item CF", models["item_item"]["hr"], models["item_item"]["ndcg"],
   models["item_item"]["p50_ms"], models["item_item"]["p95_ms"], models["item_item"]["size_mb"]],
]
print(tabulate(table, headers=["Model","HR@K","NDCG@K","p50 (ms)","p95 (ms)","Size (MB)"], tablefmt="github"))

import json
from tabulate import tabulate

with open("/content/model_registry/v0.1/offline_results.json") as f:
    r = json.load(f)

rows = [
    ["Popularity",  r["models"]["popularity"]["hr"],  r["models"]["popularity"]["ndcg"],
     r["models"]["popularity"]["p50_ms"], r["models"]["popularity"]["p95_ms"], r["models"]["popularity"]["size_mb"]],
    ["Item-Item CF", r["models"]["item_item"]["hr"], r["models"]["item_item"]["ndcg"],
     r["models"]["item_item"]["p50_ms"], r["models"]["item_item"]["p95_ms"], r["models"]["item_item"]["size_mb"]],
]
print(tabulate(rows, headers=["Model","HR@K","NDCG@K","p50 (ms)","p95 (ms)","Size (MB)"], tablefmt="github"))

