model_version: "v0.7"
created_at: "2025-11-26T08:25:23Z"
artifact: "model.joblib"
data_snapshot_id: "nightly"
pipeline_git_sha: "f8230f31ca6fd81bf429a29067db73f8e00fc3ea"
container_image_digest: "unknown"
metrics: {}
