version: v0.2
created_at: "2025-11-10T23:45:00Z"
artifact: model.joblib
data_snapshot_id: "snap-001"
pipeline_git_sha: "abc123"
container_image_digest: "local-dev"
metrics:
  map@10: 0.12
  auc: 0.71
