model_version: "v0.10"
created_at: "2025-12-02T08:26:42Z"
artifact: "model.joblib"
data_snapshot_id: "nightly"
pipeline_git_sha: "8ed68f6659bae51e19b524bcfd903ad69ba42292"
container_image_digest: "unknown"
metrics: {}
