model_version: "v0.10"
created_at: "2025-12-09T08:26:31Z"
artifact: "model.joblib"
data_snapshot_id: "nightly"
pipeline_git_sha: "ce91d8f20bf6530b8083b2455617997e15f48f4d"
container_image_digest: "unknown"
metrics: {}
