model_version: "v0.10"
created_at: "2025-12-16T08:27:36Z"
artifact: "model.joblib"
data_snapshot_id: "nightly"
pipeline_git_sha: "3a7602108c0a6a756fbcba034af071f13d1ea498"
container_image_digest: "unknown"
metrics: {}
