model_version: "v0.10"
created_at: "2025-12-15T08:29:10Z"
artifact: "model.joblib"
data_snapshot_id: "nightly"
pipeline_git_sha: "6fef2386ebfd159e5ca361af41c5dc88646f875b"
container_image_digest: "unknown"
metrics: {}
