model_version: "v0.10"
created_at: "2025-12-05T08:25:00Z"
artifact: "model.joblib"
data_snapshot_id: "nightly"
pipeline_git_sha: "f2be877411e57ddeb9582acd869371aeafa40edb"
container_image_digest: "unknown"
metrics: {}
