model_version: "v0.10"
created_at: "2025-12-07T08:21:53Z"
artifact: "model.joblib"
data_snapshot_id: "nightly"
pipeline_git_sha: "88f4de4d163903937180ab5fb5b71c84db2c2ed9"
container_image_digest: "unknown"
metrics: {}
