model_version: "v0.10"
created_at: "2025-11-30T08:21:50Z"
artifact: "model.joblib"
data_snapshot_id: "nightly"
pipeline_git_sha: "508d5ffd9947e588226349e097b02682a3b931ea"
container_image_digest: "unknown"
metrics: {}
