model_version: "v0.10"
created_at: "2025-12-12T08:26:45Z"
artifact: "model.joblib"
data_snapshot_id: "nightly"
pipeline_git_sha: "0f24ec997db0c0d48d9b1cbee13b5850192ac2d8"
container_image_digest: "unknown"
metrics: {}
