model_version: "v0.10"
created_at: "2025-12-17T08:27:23Z"
artifact: "model.joblib"
data_snapshot_id: "nightly"
pipeline_git_sha: "589be7498509faa34ccb4c3c5917e5f7ce077d32"
container_image_digest: "unknown"
metrics: {}
